### ISSUE TITLE
TagData.loadItems

### ISSUE THREAD

**Issue by smad2005** [smad2005/PoeHud#14]
![snymok96](https://cloud.githubusercontent.com/assets/1619549/9408614/1dcb6092-481d-11e5-9c27-188385cd7837.PNG)

**Comment by smad2005** [comment]
```
~~  Program exited with message:
System.ArgumentException: An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at PoeHUD.Poe.FilesInMemory.TagsDat.loadItems()
at PoeHUD.Poe.FilesInMemory.TagsDat..ctor(Memory m, Int32 address)
at PoeHUD.Controllers.FsController..ctor(Memory mem)
at PoeHUD.Controllers.GameController..ctor(Memory memory)
at PoeHUD.Program.Main(String[] args)
```
